import kotlin.math.sqrt
import kotlin.math.abs

typealias double = Double
typealias string = String
inline fun <reified T> mlo(vararg elements: T) = mutableListOf(*elements)

/**
 * generated by kotlincputil@tauros
 */
fun main(args: Array<String>) {
    // https://codeforces.com/problemset/problem/908/C
    // 找和之前圆心距离为2r时最大的y即可
    val (n, r) = readln().split(" ").map(string::toInt)
    val xs = readln().split(" ").map(string::toInt).toIntArray()

    val ans = buildString {
        val centers = mlo<Pair<double, double>>()
        for (x in xs) {
            var res = r.toDouble()
            for ((x1, y1) in centers) if (abs(x - x1) <= 2 * r) {
                val len2 = r.toDouble() * r * 4 - (x.toDouble() - x1) * (x.toDouble() - x1)
                val y = y1 + sqrt(len2)
                res = maxOf(res, y)
            }
            append(string.format("%.8f ", res))
            centers.add(x.toDouble() to res)
        }
    }
    println(ans)
}