inline fun findFirst(n: Int, judge: (Int) -> Boolean): Int {
    var l = 0
    var r = n
    while (l < r) {
        val mid = l + (r - l) / 2
        if (judge(mid)) r = mid
        else l = mid + 1
    }
    return l
}
typealias string = String
inline fun dar(size: Int, init: (Int) -> Double = { 0.0 }) = DoubleArray(size) { init(it) }

/**
 * generated by kotlincputil@tauros
 */
fun main(args: Array<String>) {
    val n = readln().toInt()
    val coords = readln().split(" ").map { it.toInt() }.sorted()
    val (max, min) = coords.last().toDouble() to coords.first().toDouble()

    var (l, r) = 0.0 to max - min
    var ans = dar(3)
    repeat(50) {
        val mid = (l + r) / 2

        val stations = dar(3)
        var pivot = 0
        repeat(3) {
            if (pivot >= n) {
                stations[it] = stations[it - 1]
                return@repeat
            }
            val pos = coords[pivot] + mid * 2
            stations[it] = coords[pivot] + mid
            pivot = findFirst(n) { coords[it] > pos }
        }
        if (pivot >= n) {
            ans = stations
            r = mid
        } else {
            l = mid
        }
    }
    println(string.format("%.6f", (l + r) / 2))
    println(buildString { for (res in ans) append(string.format("%.6f ", res)) })
}