fun pow(a: Double, p: Int): Double {
    var res = 1.0
    var base = a
    var rest = p
    while (rest > 0) {
        if (rest and 1 == 1) res *= base
        base *= base
        rest = rest shr 1
    }
    return res
}
typealias string = String

/**
 * generated by kotlincputil@tauros
 */
fun main(args: Array<String>) {
    // https://codeforces.com/problemset/problem/453/A
    // 摇出[1, max]的概率减去摇出[1, max-1]的概率，然后快速幂一下即可
    val (m, n) = readln().split(" ").map(string::toInt)

    var ans = 0.0
    for (max in m downTo 1) {
        val probIn = pow(max.toDouble() / m, n)
        val probOut = pow((max - 1.0) / m, n)
        val prob = probIn - probOut
        ans += prob * max
    }
    println(string.format("%.8f", ans))
}