/* Generated by powerful Codeforces Tool
 * You can download the binary file in here https://github.com/xalanq/cf-tool (Windows, macOS, Linux)
 * Author: zhengyi20thu
 * Time: 2024-05-25 10:02:02
 **/

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;

int main()
{
    ios::sync_with_stdio(false);
    cin.tie(0);
    int n;
    cin >> n;
    vector<int> a(n);
    set<pair<ll, int>> s;
    for (int i = 0; i < n; i++)
    {
        cin >> a[i];
        s.insert({a[i], i});
    }
    vector<ll> deleted(n, 0);

    while (true)
    {
        bool tag = false;
        for (auto it = s.begin(); it != s.end(); it++)
        {
            auto tmp = it;
            tmp++;
            if (tmp == s.end())
            {
                deleted[it->second] = it->first;
                tag = true;
                break;
            }
            if (it->first == tmp->first)
            {
                auto latter_pos = tmp->second;
                auto latter_val = tmp->first;
                s.erase(it);
                s.erase(tmp);
                s.insert({latter_val * 2, latter_pos});
                break;
            }
            else
            {
                deleted[it->second] = it->first;
                s.erase(it);
                break;
            }
        }
        if (tag)
        {
            break;
        }
    }
    vector<ll> ans;
    for (int i = 0; i < n; i++)
    {
        if (deleted[i] != 0)
        {
            ans.push_back(deleted[i]);
        }
    }
    cout << ans.size() << endl;
    for (auto x : ans)
    {
        cout << x << " ";
    }
    return 0;
}
